### ISSUE TITLE
Pluigin no longer compatible 

### ISSUE THREAD

**Issue by servantthought** [SkyLightMCPE/Wild#1]
Server] Server thread/INFO Loading source plugin Wild v0.1_beta
22.04 03:42:35 [Server] INFO Fatal error: Declaration of SkyLightMCPE\Main::onCommand(pocketmine\command\CommandSender $s, pocketmine\command\Command $cmd, $label, array $args) must be compatible with pocketmine\plugin\PluginBase::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool in /plugins/Wild-master/src/SkyLightMCPE/Main.php on line 53

**Comment by servantthought** [comment]
I added :bool

But now it works but I still take fall damage

public function onDamage(EntityDamageEvent $event){
       if($event->getEntity() instanceof Player){
           if(isset($this->iswildin[$event->getEntity->getName()])){
               $p = $event->getEntity();
               unset($this->iswildin[$p->getName()]);
                     $event->setCancelled();
Is not working

**Comment by samuelctn** [comment]
solved.

**Comment by servantthought** [comment]
Yeah I add :bool and nick added a tp highest block...code because your fall damage was not canceling... 

Jose Luis Alvarez Jr. 
 
  On Mon, Apr 23, 2018 at 2:18 PM, Samy<notifications@github.com> wrote:   
solved.
